proyecto1/applications/departamento/urls.py
from django.urls import path
from applications.departamento import views


app_name='departamento_app'

urlpatterns = [
    path('newDepartamento/',
         views.NewDepartamento.as_view(),
         name='newDepartamento'),

    path('departamento_lista/',
    views.DepartamentoListView.as_view(),
    name='departamento_lista')
]

proyecto1/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from applications.persona import views

app_name='persona_app'

urlpatterns = [
    #path('',
    #     views.Inicio.as_view(),
    #     name='inicio'
    #),
    path( 'persona/verTodosEmpleados/',
          views. VerTodosEmpleados_listView.as_view(),
          name='persona-verTodosEmpleados'), 
    path('persona/verDetalleEmpleado/<pk>',
         views.DetalleEmpleado_detailView.as_view(),
         name='persona-verDetalleEmpleado'),

    path('persona/administrarEmpleados/',
         views.AdministrarEmpleados_listView.as_view(),
         name='persona-administrarEmpleados'
         ),

    path('editarEmpleado/<pk>',
         views.EditarEmpleado.as_view(),
         name='editarEmpleado'
         ),

    path('eliminarEmpleado/<pk>',
         views.EliminarEmpleado.as_view(),
         name='eliminarEmpleado'
         ),

    path('empleadosPorArea/<area>/',
         views.EmpleadosPorArea_listView.as_view(),
         name='empleadosPorArea'
         ),


    path('addEmpleado/',
         views.AddEmpleado.as_view(),
         name='addEmpleado'),


]

proyecto1/proyecto1/urls.py
from django.contrib import admin
from django.urls import path,re_path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluyendo las URLS de la app departamento
    path('', include( 'applications.departamento.urls') ),
    path('', include( 'applications.persona.urls') ),
    path('', include( 'applications.home.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto1/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    # El primer parametro es el texto que aparecera en el administrador de django
    name=models.CharField('Nombre',max_length=50)
    shor_name=models.CharField('Nombre corto',max_length=20)

    #valor por defecto es igual a False
    anulate=models.BooleanField('Anulado',default=False)

    def __str__(self):
        return '{} - {} - {}'.format(self.id,self.name,self.shor_name)

proyecto1/applications/departamento/forms.py
from django import forms
from applications.persona.models import Habilidades

class NewDepartamentoForm(forms.Form):
    nombre=forms.CharField(max_length=50)
    apellidos=forms.CharField(max_length=50)
    departamento=forms.CharField(max_length=50)
    shorname=forms.CharField(max_length=20)

    avatar=forms.ImageField()
    habilidades=forms.ModelMultipleChoiceField(Habilidades.objects.all())

proyecto1/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import ListView
from  .forms import NewDepartamentoForm

from .models import Departamento
from applications.persona.models import Empleado, Habilidades
from django.urls import reverse_lazy

class DepartamentoListView(ListView):
    model=Departamento
    template_name = 'departamento/listaDepartamentos.html'
    context_object_name = 'datos'


# Create your views here.
class NewDepartamento(FormView):
    template_name = 'departamento/newDepartamento.html'
    form_class = NewDepartamentoForm
    success_url = reverse_lazy('departamento_app:departamento_lista')

    def form_valid(self, form):
        print("***ESTAMOS EN EL FORM VALID")
        nombre=form.cleaned_data['nombre']
        apellido=form.cleaned_data['apellidos']
        departamento=form.cleaned_data['departamento']
        shorname=form.cleaned_data['shorname']
        avatar=form.cleaned_data['avatar']
        habilidades=form.cleaned_data['habilidades']

        print("HABILIDADES",habilidades)

        depa=Departamento(
            name=departamento,
            shor_name=shorname,
        )
        depa.save()

        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1', # Administrador
            departamento=depa,
            avatar=avatar,
        ).habilidades.set(habilidades)

        return super(NewDepartamento,self).form_valid(form)

proyecto1/templates/departamento/listaDepartamentos.html
{% extends 'base.html' %}
{% block title %} departamentos {% endblock title%}
{% block body %}
{% include 'includes/cabezal.html' %}
<h1></h1>
<div class="grid-container">
    <div class="cell">
        <h1>Lista de Departamentos</h1>
    </div>
    <div class="cell">
        <table>
            <tbody>
            {% for departamento in datos%}
            <tr>
                <td> {{departamento.name}} </td>
                <td> {{departamento.shor_name}}</td>
                <td>
                    <a class="button warning"
                       href="{% url 'persona_app:empleadosPorArea' departamento.shor_name %}"
                    > Ver empleados</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock body %}

proyecto1/templates/departamento/newDepartamento.html
{% extends 'base.html' %}
{% block title %} creando departamento {% endblock title %}
{% block body %}
{% include 'includes/cabezal.html' %}
<div class="grid-container">
    <div class="grid-x">
        <form method="post"  enctype="multipart/form-data" >{% csrf_token %}
            <h2 class="cell" >Datos de departamento</h2>
            <div class="callout">
                <label class="cell"> Departamento:{{form.departamento}} </label>
                <label class="cell" >  Abreviatura:{{form.shorname}} </label>
            </div>
            <h2 class="cell"> Administrador del departamento </h2>
            <div class="callout">
                <label class="cell" >  Nombre:{{form.nombre}} </label>
                <label class="cell" > Apellidos:{{form.apellidos}} </label>
                <label class="cell" > Habilidades:{{form.habilidades}} </label>
                <label class="cell" > Avatar:{{form.avatar}} </label>
            </div>
            <button class="success button" type="submit">Agregar</button>
        </form>
    </div>
</div>
{% endblock body %}