proyecto1/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from applications.persona import views

app_name='persona_app'

urlpatterns = [
    #path('',
    #     views.Inicio.as_view(),
    #     name='inicio'
    #),
    path( 'persona/verTodosEmpleados/',
          views. VerTodosEmpleados_listView.as_view(),
          name='persona-verTodosEmpleados'), 
    path('persona/verDetalleEmpleado/<pk>',
         views.DetalleEmpleado_detailView.as_view(),
         name='persona-verDetalleEmpleado'),

    path('persona/administrarEmpleados/',
         views.AdministrarEmpleados_listView.as_view(),
         name='persona-administrarEmpleados'
         ),

    path('editarEmpleado/<pk>',
         views.EditarEmpleado.as_view(),
         name='editarEmpleado'
         ),

    path('eliminarEmpleado/<pk>',
         views.EliminarEmpleado.as_view(),
         name='eliminarEmpleado'
         ),

    path('empleadosPorArea/<area>/',
         views.EmpleadosPorArea_listView.as_view(),
         name='empleadosPorArea'
         ),


    path('addEmpleado/',
         views.AddEmpleado.as_view(),
         name='addEmpleado'),


]

proyecto1/proyecto1/urls.py
from django.contrib import admin
from django.urls import path,re_path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluyendo las URLS de la app departamento
    path('', include( 'applications.departamento.urls') ),
    path('', include( 'applications.persona.urls') ),
    path('', include( 'applications.home.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto1/applications/persona/models.py
from django.db import models
from applications.departamento.models import  Departamento

# Create your models here.

class Habilidades(models.Model):
    habilidad=models.CharField('Habilidad:',max_length=50)

    class Meta:
        # como referirnos a una instancia
        verbose_name='Habilidad'
        # como referirnos a todas nuestras instancias
        verbose_name_plural='Habilidades de empleados'
        # ordenando de forma descenente
        ordering= ['-id']
        # no se permite que la combinación de los atributos de
        # la lista den el mismo resultado
        unique_together=['habilidad','id']
    def __str__(self):
        return '{}-{}'.format(self.id,self.habilidad)

class Empleado(models.Model):
    JOB_CHOICES=(
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),        
        ('2', 'MARKETING DIGITAL'),
        ('3','PROGRAMADOR'),
        ('4','GESTOR DE VENTAS'),
        ('5','RECLUTADOR'),
        ('6','LIDER DE PROYECTO'),
        ('7', 'OTRO'),
    )
    first_name=models.CharField('Nombre:',max_length=50)
    last_name=models.CharField('Apellido:',max_length=50)
    job=models.CharField('Trabajo:', max_length=1, choices=JOB_CHOICES)
    departamento=models.ForeignKey(Departamento,on_delete=models.CASCADE)
    habilidades=models.ManyToManyField(Habilidades)
    avatar=models.ImageField(upload_to='empleado',blank=True,null=True)
    def __str__(self):
        return ' {} {}  '.format(self.first_name,self.last_name)

proyecto1/applications/persona/views.py
from django.views.generic import (ListView,DetailView,CreateView,
                                  TemplateView,UpdateView,DeleteView)
from .models import Empleado

from django.urls import reverse_lazy

class VerTodosEmpleados_listView(ListView):
    '''
    Mostrar una lista con todos los empleados
    '''

    template_name ='persona/todosEmpleados.html'
    model = Empleado
    context_object_name = 'datos'
    paginate_by = 10

    def get_queryset(self):
        '''
        Si se sobreescribe este metodo ya no sera necesario indicarle
        un modelo a la clase, ya que este metodo es el que decide
        que información regresar
        '''

        palabraClave=self.request.GET.get('kword','')
        lista= Empleado.objects.filter(
            first_name__icontains=palabraClave
        )
        return lista


class DetalleEmpleado_detailView(DetailView):
    template_name ='persona/detalleEmpleado.html'
    model = Empleado


class AdministrarEmpleados_listView(ListView):
    model = Empleado
    template_name = 'persona/administracionEmpleados.html'
    context_object_name = 'datos'
    paginate_by = 10

class EditarEmpleado(UpdateView):
    template_name = 'persona/editarEmpleado.html'
    model = Empleado
    fields = ('__all__')
    success_url = reverse_lazy('persona_app:persona-administrarEmpleados')


class EliminarEmpleado(DeleteView):
    template_name = 'persona/eliminarEmpleado.html'
    model = Empleado
    success_url = reverse_lazy('persona_app:persona-administrarEmpleados')
    context_object_name = 'empleadoEliminar'


class EmpleadosPorArea_listView(ListView):
    template_name ='persona/empleadosPorArea.html'
    model = Empleado
    context_object_name = 'datos'
    def get_queryset(self):
        '''
        Retornara el resultado de un filtro de busqueda
        :return:
        siempre debe retornar una lista
        '''

        area=self.kwargs['area']
        lista= Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista


class AddEmpleado(CreateView):
    template_name = 'persona/addPersona.html'
    model = Empleado
    fields = ('__all__')
    # significa que se rederigira a la misma pagina
    success_url = reverse_lazy('persona_app:persona-administrarEmpleados')


class BusquedaPerfiles(ListView):
    template_name = 'persona/busquedaPerfiles.html'
    context_object_name = 'datos'
    model = Empleado
    paginate_by = 3
    ordering = 'first_name'

    def get_queryset(self):
        perfil=self.request.GET.get('nombre_perfil_x','')
        lista= Empleado.objects.filter(
            departamento__shor_name=perfil
        )
        if len(lista)<1:
            lista=['Sin resultados']
        return lista

proyecto1/templates/persona/addPersona.html
{% extends 'base.html' %}
{% block title %} Agregar empleado {% endblock title %}
{% block body %}
{% include 'includes/cabezal.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x">
        <h1 class="cell" >Registro de empleado</h1>
        <!--FORMULARIO DE DATOS DEL EMPLEADO-->
        <form method="post" class="grid-x grid-margin-x"  enctype="multipart/form-data">{% csrf_token %}
            <div class="cell large-6">
                <label> Nombre: {{form.first_name}}</label>
            </div>
            <div class="cell large-6">
                <label> Apellido: {{form.last_name}}</label>
            </div>
            <div class="cell large-6">
                <label> Trabajo: {{form.job}}</label>
            </div>
            <div class="cell large-6">
                <label> Departamento: {{form.departamento}}</label>
            </div>
            <div class="cell large-6">
                <label> Habilidades: {{form.habilidades}}</label>
            </div>
            <div class="cell large-">
                <label> Imagen: {{form.avatar}}</label>
            </div>
            <div class="cell">
                <button type="submit" class="success button">Agregar</button>
            </div>
        </form>
        <!--FIN DEL FORMULARIO DE DATOS DEL EMPLEADO-->
    </div>
</div>
{% endblock body %}

proyecto1/templates/persona/administracionEmpleados.html
{% extends 'base.html' %}
{% block title %} los empleados {% endblock title %}

{% block body %}
{% include 'includes/cabezal.html' %}


<div class="grid-container">
    <div class="grid-x">
        <div clas="cell">
            <h1> Empleados </h1>
        </div>
        <div class="cell">
            <!--TABLA DE DATOS: -->
            <div class="cell">
                <table>
                    <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th width="150">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTOS</th>
                        <th width="150">ACCION</th>
                    </tr>
                  </thead>
                    <tbody>
                  {% for empleado in datos %}
                    <tr>
                        <td>{{empleado.id}}</td>
                        <td>{{empleado.first_name}}</td>
                        <td>{{empleado.last_name}}</td>
                        <td>{{empleado.departamento}}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:editarEmpleado' empleado.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminarEmpleado' empleado.id %}">Eliminar</a>
                        </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            </div>
            <!-- FIN DE TABLA DE DATOS -->

        <!-- PAGINACION -->
        {% if is_paginated %}
            <div class="cell">
                <nav aria-label="Pagination">
                  <ul class="pagination">
                      {% if page_obj.has_previous %}
                        <li class="pagination-previous ">
                            <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
                        </li>
                      {% endif %}

                      {% for pagina in paginator.page_range %}
                        {% ifequal pagina page_obj.number %}
                            <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                            <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                        {% endifequal %}
                      {% endfor %}

                      {% if page_obj.has_next %}
                        <li class="pagination-next ">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                      {% endif %}
                  </ul>
                </nav>
            </div>
        {% endif %}
        <!-- FIN DE PAGINACION-->
        </div>
    </div>
</div>
{% endblock body %}

proyecto1/templates/persona/detalleEmpleado.html
{% extends 'base.html' %}
{% load static %}
{% block title %} edicion {% endblock title%}
{% block body %}
{% include 'includes/cabezal.html' %}
<div class="grid-container">
    <div class="grid-x align-center">
        <div class="cell large-4 card" style="width: 300px;">
            <div class="card-divider">
                {{object.get_job_display}}
            </div>
            {% if object.avatar %}
                <img src="{{object.avatar.url}}">
            {% else %}
                <img src="{% static 'img/sinImagen.jpg' %}">
            {% endif %}
            <div class="card-section">
                <h4>{{object.first_name}} {{object.last_name}}</h4>
                <p>{{object.departamento.shor_name}}</p>
                <p><span class="label">Habilidades: </span></p>
                <ul class="vertical menu" >
                    {% for h in object.habilidades.all %}
                        <li> {{h.habilidad}} </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

proyecto1/templates/persona/editarEmpleado.html
{% extends 'base.html' %}
{% block title %} edicion {% endblock title%}
{% block body %}
{% include 'includes/cabezal.html' %}
<div class="grid-container">
    <div class="grid-x">
        <div class="cell"> <h1>Edicion de datos</h1> </div>
        <div class="cell">
        <!--FORMULARIO DE DATOS DEL EMPLEADO-->
        <form method="post" class="grid-x grid-margin-x"  enctype="multipart/form-data">{% csrf_token %}
            <div class="cell large-6">
                <label> Nombre: {{form.first_name}}</label>
            </div>
            <div class="cell large-6">
                <label> Apellido: {{form.last_name}}</label>
            </div>
            <div class="cell large-6">
                <label> Trabajo: {{form.job}}</label>
            </div>
            <div class="cell large-6">
                <label> Departamento: {{form.departamento}}</label>
            </div>
            <div class="cell large-6">
                <label> Habilidades: {{form.habilidades}}</label>
            </div>
            <div class="cell large-">
                <label> Imagen: {{form.avatar}}</label>
            </div>
            <div class="cell">
                <button type="submit" class="success button">Guardar cambios</button>
            </div>
        </form>
        <!--FIN DEL FORMULARIO DE DATOS DEL EMPLEADO-->
        </div>
    </div>
</div>
{% endblock body %}

proyecto1/templates/persona/eliminarEmpleado.html
{% extends 'base.html' %}
{% block title %}  eliminar empleado {% endblock title %}
{% block body %}

{% include 'includes/cabezal.html'%}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Eliminación de empleado: {{empleadoEliminar.first_name}}</h1>
        <form class="cell" method="post">{% csrf_token %}
            <div class="callout alert">
                <h4>¿Deseas eliminar a este empleado?</h4>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>
{% endblock body %}

proyecto1/templates/persona/empleadosPorArea.html
{% extends 'base.html' %}
{% block title %} empleados {% endblock title %}

{% block body %}
{% include 'includes/cabezal.html' %}

<!-- grid-container para que se centren los elemento -->
<div class="grid-container">
    <!-- Para que se puedan organizar en tablas los renglones-->
    <div class="grid-x">
        <div class="cell">
            <h1>Empleados de la area buscada: </h1>
        </div>

        <!--TABLA DE DATOS: -->
        <div class="cell">
            <table>
                <thead>
                <tr>
                    <th width="50">ID</th>
                    <th width="150">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTOS</th>
                    <th width="150">ACCION</th>
                </tr>
              </thead>
                <tbody>
              {% for empleado in datos %}
                <tr>
                    <td>{{empleado.id}}</td>
                    <td>{{empleado.first_name}}</td>
                    <td>{{empleado.last_name}}</td>
                    <td>{{empleado.departamento}}</td>
                    <td>
                        <a class="button warning" href="{% url 'persona_app:persona-verDetalleEmpleado' empleado.id %}">Ver</a>
                    </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
        <!-- FIN DE TABLA DE DATOS -->

    </div>
    <!-- fin del 'grid-x' -->
</div>
<!-- fin del grid-container -->

{% endblock body %}

</div>

proyecto1/templates/persona/todosEmpleados.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Empleados {% endblock title %}
{% block body %}
{% include 'includes/cabezal.html' %}

<div class="grid-container">

    <div class="grid-x" >
        <h1 class="cell"> Empleados</h1>

        <!-- Buscar empleados, como esto hace una consulta se usa
         un form, y aparte el metodo 'get' de este mismo -->
        <form class="cell grid-x grid-margin-x" method="get">{% csrf_token %}
            <div class="cell large-7">
                <!-- El contenido del input contenda informacion importante de la peticion que hace
                el usuario, por lo cual es necesario especificarle un 'id' y 'name'-->
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <!--El tipo del boton debe ser: 'submit' ya que al dar clic sobre
                el se desea enviar una peticion al servidor -->
                <button type="submit" class="success button">Buscar</button>
            </div>

        </form>
         <!-- Fin de buscar empleados -->

        <!--TABLA DE DATOS: -->
        <div class="cell">
            <table>
                <thead>
                <tr>
                    <th width="50">ID</th>
                    <th width="150">NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTOS</th>
                    <th width="150">ACCION</th>
                </tr>
              </thead>
                <tbody>
              {% for empleado in datos %}
                <tr>
                    <td>{{empleado.id}}</td>
                    <td>{{empleado.first_name}}</td>
                    <td>{{empleado.last_name}}</td>
                    <td>{{empleado.departamento}}</td>
                    <td>
                        <a class="button warning" href="{% url 'persona_app:persona-verDetalleEmpleado' empleado.id %}">Ver</a>
                    </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
        <!-- FIN DE TABLA DE DATOS -->

        <!-- PAGINACION -->
        {% if is_paginated %}
            <div class="cell">
                <nav aria-label="Pagination">
                  <ul class="pagination">
                      {% if page_obj.has_previous %}
                        <li class="pagination-previous ">
                            <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
                        </li>
                      {% endif %}

                      {% for pagina in paginator.page_range %}
                        {% ifequal pagina page_obj.number %}
                            <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                            <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                        {% endifequal %}
                      {% endfor %}

                      {% if page_obj.has_next %}
                        <li class="pagination-next ">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                      {% endif %}
                  </ul>
                </nav>
            </div>
        {% endif %}
        <!-- FIN DE PAGINACION-->
    </div>
    <!--FIN DEL 'grid-x'  -->

{% endblock body %}