proyecto1/applications/departamento/urls.py
from django.urls import path
from applications.departamento import views


app_name='departamento_app'

urlpatterns = [
    path('newDepartamento/',
         views.NewDepartamento.as_view(),
         name='newDepartamento'),

    path('departamento_lista/',
    views.DepartamentoListView.as_view(),
    name='departamento_lista')
]

proyecto1/applications/home/urls.py
from django.urls import path
from .  import views
app_name='home_app'

urlpatterns = [
    path('',
        views.Index.as_view(),
        name='index'
        )
]

proyecto1/applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from applications.persona import views

app_name='persona_app'

urlpatterns = [
    #path('',
    #     views.Inicio.as_view(),
    #     name='inicio'
    #),
    path( 'persona/verTodosEmpleados/',
          views. VerTodosEmpleados_listView.as_view(),
          name='persona-verTodosEmpleados'), 
    path('persona/verDetalleEmpleado/<pk>',
         views.DetalleEmpleado_detailView.as_view(),
         name='persona-verDetalleEmpleado'),

    path('persona/administrarEmpleados/',
         views.AdministrarEmpleados_listView.as_view(),
         name='persona-administrarEmpleados'
         ),

    path('editarEmpleado/<pk>',
         views.EditarEmpleado.as_view(),
         name='editarEmpleado'
         ),

    path('eliminarEmpleado/<pk>',
         views.EliminarEmpleado.as_view(),
         name='eliminarEmpleado'
         ),

    path('empleadosPorArea/<area>/',
         views.EmpleadosPorArea_listView.as_view(),
         name='empleadosPorArea'
         ),


    path('addEmpleado/',
         views.AddEmpleado.as_view(),
         name='addEmpleado'),


]

proyecto1/proyecto1/urls.py
from django.contrib import admin
from django.urls import path,re_path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #incluyendo las URLS de la app departamento
    path('', include( 'applications.departamento.urls') ),
    path('', include( 'applications.persona.urls') ),
    path('', include( 'applications.home.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyecto1/templates/includes/cabezal.html
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a style="{% if request.resolver_match.url_name == 'index' %}font-weight:bold; font-size:20px; color:#0FABD5;{% endif %}" href="{% url 'home_app:index' %}" >
          Pagina principal
        </a>
      </li>

      <li>
        <a style="{% if request.resolver_match.url_name == 'persona-verTodosEmpleados' %}font-weight:bold; font-size:20px; color:#0FABD5;{% endif %}" href="{% url 'persona_app:persona-verTodosEmpleados' %}" >
          Ver empleados
        </a>  

      <li>
        <a style="{% if request.resolver_match.url_name == 'persona-administrarEmpleados' %}font-weight:bold; font-size:20px; color:#0FABD5;{% endif %}" href="{% url 'persona_app:persona-administrarEmpleados' %}" >
          Administrar empleados
        </a>        
      </li>

      <li>
        <a style="{% if request.resolver_match.url_name == 'departamento_lista' %}font-weight:bold; font-size:20px; color:#0FABD5;{% endif %}" href="{% url 'departamento_app:departamento_lista' %}" >
          Ver Departamentos
        </a>  
      </li>

      <li>
      <a style="{% if request.resolver_match.url_name == 'newDepartamento' %}font-weight:bold; font-size:20px; color:#0FABD5;{% endif %}" href="{% url 'departamento_app:newDepartamento' %}">
        Agregar departamento
      </a>       
      </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><a type="button" class="button" href="{% url 'persona_app:addEmpleado' %}">Registrar a un nuevo empleado</a></li>
    </ul>
  </div>
</div>